name: greenlight
services:
  api:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: greenlight-app
    container_name: greenlight-api
    ports:
      - "127.0.0.1:${SERVER_PORT}:${SERVER_PORT}"
    expose:
      - "${METRICS_PORT}"
    restart: unless-stopped

    env_file:
      - .env
    environment:
      POSTGRES_HOST: "postgres"
      REDIS_HOST: "redis"
      SERVER_HOST: "0.0.0.0"
      METRICS_ENABLED: "true"
    networks:
      - greenlight-network

    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:$$SERVER_PORT/v1/healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  prometheus:
    build:
      context: ./docker/prometheus
      dockerfile: Dockerfile
    image: greenlight-prometheus:v3.14.0
    container_name: greenlight-prometheus
    ports:
      - "127.0.0.1:${PROMETHEUS_PORT}:9090"
    restart: unless-stopped

    environment:
      METRICS_PORT: ${METRICS_PORT}
    volumes:
      - prometheus-data:/prometheus
    networks:
      greenlight-network:

    depends_on:
      api:
        condition: service_healthy

    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:18.4
    container_name: greenlight-postgres
    expose:
      - "5432"
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - greenlight-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    image: greenlight-redis:8.8
    container_name: greenlight-redis
    expose:
      - "6379"
    restart: unless-stopped

    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - greenlight-network

    healthcheck:
      # healthcheck to see if redis can write
      test: [ "CMD-SHELL", "REDISCLI_AUTH=$$REDIS_PASSWORD redis-cli --raw incr healthcheck" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  greenlight-network:

volumes:
  pgdata:
  redis-data:
  prometheus-data:
